/**
 * Module definitions for the QuizWhiz application.
 * <p>
 * This module provides the core functionality for the QuizWhiz application, including
 * user authentication, quiz management, and data persistence.
 * <p>
 * The aim of this project is to develop a personal AI tutor application for students to study and understand learning material. The AI will assist in the learning of the content and materials the user discusses and provides. Quizzes can be generated by the AI so that the user can test their knowledge on studied topics and receive feedback on areas which can be improved Users will be able to customise the AI model to suit their needs, so that it’s responses are at a specific education level, or so that quizzes can be of a certain length or difficulty.
 *
 * @author Justin.
 * @author Joshua M.
 * @author Kiel P.
 * @author Alex O.
 * @author Jack K.
 * @author Mason M.
 * @see ai.tutor.cab302exceptionalhandlers.QuizWhizApplication
 */
module ai.tutor.cab302exceptionalhandlers {
    requires transitive javafx.controls;
    requires transitive javafx.fxml;

    requires org.xerial.sqlitejdbc;
    requires org.slf4j;
    requires password4j;
    requires ollama4j;
    requires java.net.http;
    requires com.google.gson;
    requires one.jpro.platform.mdfx;

    opens ai.tutor.cab302exceptionalhandlers to javafx.fxml;
    opens ai.tutor.cab302exceptionalhandlers.controller to javafx.fxml;
    opens ai.tutor.cab302exceptionalhandlers.Utils to com.google.gson;

    exports ai.tutor.cab302exceptionalhandlers;
    exports ai.tutor.cab302exceptionalhandlers.model;
    exports ai.tutor.cab302exceptionalhandlers.controller;
    exports ai.tutor.cab302exceptionalhandlers.Utils;
    exports ai.tutor.cab302exceptionalhandlers.builders;
    exports ai.tutor.cab302exceptionalhandlers.factories;
    exports ai.tutor.cab302exceptionalhandlers.types;
}
